print("1")
dict={"Mady":"8","Roger":"5","Paul":"5","Lucky":"7"}
print(dict)
print("2")
dict={"Ken":"8","Andre":"7","Smith":"6"}
print(dict)
print("3")
dict={"Mady":"8","Roger":"5","Paul":"5","Lucky":"7"}
new_dict={"Ken":"8","Andre":"7","Smith":"6"}
dict.update(new_dict)
print(dict)
print("4")
dict["Roger"]=8
dict["Paul"]=8
dict["Smith"]=8
print(dict)
print("5")
a={"Mady":"8","Roger":"8","Paul":"8","Ken":"8","Smith":"8"}
for data in a:
	print(data)